import './styles/dashboard.css';
import './styles/transition-dashboard.css';
import { applyBrand } from './brand';
import { mockBrand, mockBroadcastRail, mockLowerThird, mockMatch, mockObs, mockShow, mockSpeedrun, mockTransitionOverlay, mockTransitionSettings } from './mock';
import { observe } from './replicant';
import { speedrunFeedIdentities, timerAction, timerElapsed } from './domain';
import { advanceBroadcastRail, normalizeBroadcastRail } from './rail';
import { normalizeTransitionSettings } from './transition';
import type { Brand, BroadcastRailState, FeedCount, FeedIdentity, HbsTransitionMode, LowerThirdState, MatchState, ObsState, RailModule, ShowMode, ShowState, SpeedrunState, SponsorItem, TransitionOverlayState, TransitionSettings } from './types';

const $ = <T extends HTMLElement>(selector:string) => document.querySelector<T>(selector);
const all = <T extends HTMLElement>(selector:string) => [...document.querySelectorAll<T>(selector)];
const toast = (message:string) => { const el=$<HTMLElement>('[data-toast]');if(!el)return;el.textContent=message;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2200); };
const value = (selector:string) => ($<HTMLInputElement|HTMLSelectElement>(selector)?.value ?? '').trim();
const setText = (selector:string,content:unknown) => {const element=$(selector);if(element)element.textContent=content==null?'':String(content);};

// Keep navigation between the two HBS panels inside the live NodeCG iframe.
// Opening these links as a browser pop-out adds standalone=true, which has no
// live Replicant connection and therefore cannot apply broadcast data.
all<HTMLAnchorElement>('a[href="setup.html"],a[href="index.html"]').forEach((link) => link.addEventListener('click', (event) => {
  event.preventDefault();
  window.location.assign(link.getAttribute('href')!);
}));

const matchRep=observe<MatchState>('match',mockMatch,(m)=>{all<HTMLInputElement>('[data-field]').forEach((el)=>{if(document.activeElement!==el)el.value=String(m[el.dataset.field as 'game'|'round'|'bestOf']??'')});(['player1','player2'] as const).forEach((side,i)=>{all<HTMLInputElement>(`[data-p${i+1}]`).forEach((el)=>{if(document.activeElement!==el)el.value=String(m[side][el.dataset[`p${i+1}`] as keyof typeof m[typeof side]]??'')});const out=$<HTMLOutputElement>(`[data-score-value="${side}"]`);if(out)out.value=String(m[side].score);setText(`[data-live-player="${side}"]`,m[side].displayName)});});
const lowerRep=observe<LowerThirdState>('lowerThird',mockLowerThird,(lower)=>{all<HTMLInputElement|HTMLSelectElement>('[data-lower]').forEach((el)=>{if(document.activeElement!==el)el.value=String(lower[el.dataset.lower as keyof LowerThirdState]??'')});setText('[data-live-lower-title]',lower.title||'Nothing queued');setText('[data-live-lower-subtitle]',lower.subtitle);});
const showRep=observe<ShowState>('show',mockShow,(show)=>{all<HTMLInputElement>('[data-show]').forEach((el)=>{if(document.activeElement!==el)el.value=String(show[el.dataset.show as keyof ShowState]??'')});all<HTMLButtonElement>('[data-mode]').forEach((button)=>button.classList.toggle('active',button.dataset.mode===show.mode));setText('[data-live-show="current"]',show.currentSegment||'Live show');setText('[data-live-show="next"]',show.nextSegment||'More programming soon');setText('[data-live-show="time"]',show.nextSegmentTime);});
let railState = mockBroadcastRail;
let sponsorDraft: SponsorItem[] = [];
const renderSponsorEditors = (sponsors: SponsorItem[]) => {
  sponsorDraft = sponsors.map((sponsor) => ({ ...sponsor }));
  const box = $('[data-sponsor-editors]');
  if (!box || box.contains(document.activeElement)) return;
  box.innerHTML = sponsorDraft.map((_, index) => `<article class="sponsor-editor" data-sponsor-editor="${index}"><div class="sponsor-editor-head"><h3>Sponsor ${index + 1}</h3><button type="button" data-remove-sponsor="${index}" class="danger">Remove</button></div><label class="check"><input type="checkbox" data-sponsor-field="enabled"> Include in rotation</label><label>Display name<input maxlength="120" data-sponsor-field="name"></label><label>Logo URL / bundle path<input maxlength="500" data-sponsor-field="logoUrl" placeholder="https://… or /bundles/…"></label></article>`).join('');
  all<HTMLElement>('[data-sponsor-editor]').forEach((panel) => {
    const sponsor = sponsorDraft[Number(panel.dataset.sponsorEditor)];
    const name = panel.querySelector<HTMLInputElement>('[data-sponsor-field="name"]');
    const logo = panel.querySelector<HTMLInputElement>('[data-sponsor-field="logoUrl"]');
    const enabled = panel.querySelector<HTMLInputElement>('[data-sponsor-field="enabled"]');
    if (name) name.value = sponsor?.name ?? '';
    if (logo) logo.value = sponsor?.logoUrl ?? '';
    if (enabled) enabled.checked = sponsor?.enabled !== false;
  });
  all<HTMLButtonElement>('[data-remove-sponsor]').forEach((button) => button.addEventListener('click', () => { sponsorDraft.splice(Number(button.dataset.removeSponsor), 1); button.blur(); renderSponsorEditors(sponsorDraft); }));
};
const railRep=observe<BroadcastRailState>('broadcastRail',mockBroadcastRail,(rail)=>{
  railState=normalizeBroadcastRail(rail);
  all<HTMLInputElement>('[data-rail]').forEach((el)=>{const key=el.dataset.rail as 'automatic'|'rotationSeconds';if(el.type==='checkbox')el.checked=Boolean(railState[key]);else if(document.activeElement!==el)el.value=String(railState[key])});
  all<HTMLInputElement>('[data-rail-module-enabled]').forEach((el)=>{el.checked=railState.enabledModules[el.dataset.railModuleEnabled as RailModule]});
  all<HTMLInputElement>('[data-donation]').forEach((el)=>{if(document.activeElement!==el)el.value=String(railState.donation[el.dataset.donation as keyof typeof railState.donation]??'')});
  const announcement=$<HTMLTextAreaElement>('[data-rail-announcement]');if(announcement&&document.activeElement!==announcement)announcement.value=railState.announcement;
  const visibility=$('[data-rail-visibility]');if(visibility)visibility.textContent=railState.visible?'On air':'Hidden';
  const current=$('[data-rail-current]');if(current)current.textContent=`${railState.activeModule}${railState.held?' · held':''}`;
  all<HTMLButtonElement>('[data-rail-module]').forEach((button)=>button.classList.toggle('active',button.dataset.railModule===railState.activeModule));
  const hold=$<HTMLButtonElement>('[data-rail-action="toggleHold"]');if(hold)hold.textContent=railState.held?'Resume rotation':'Hold rotation';
  renderSponsorEditors(railState.sponsors);
});
let speedrunState = mockSpeedrun;
const renderDashboardTimer=()=>{const elapsed=timerElapsed(speedrunState.timer);const hours=Math.floor(elapsed/3_600_000);const minutes=Math.floor(elapsed/60_000)%60;const seconds=Math.floor(elapsed/1000)%60;const tenths=Math.floor(elapsed/100)%10;const out=$<HTMLOutputElement>('[data-speedrun-timer]');if(out)out.value=`${hours?`${String(hours).padStart(2,'0')}:`:''}${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}.${tenths}`;};
const speedrunRep=observe<SpeedrunState>('speedrun',mockSpeedrun,(run)=>{speedrunState=run;const identities=speedrunFeedIdentities(run);all<HTMLInputElement>('[data-speedrun]').forEach((el)=>{if(document.activeElement!==el)el.value=String(run[el.dataset.speedrun as keyof SpeedrunState]??'')});all<HTMLInputElement>('[data-speedrun-toggle]').forEach((el)=>{el.checked=Boolean(run[el.dataset.speedrunToggle as keyof SpeedrunState])});all<HTMLInputElement>('[data-feed-identity]').forEach((el)=>{if(document.activeElement===el)return;const [position,field]=el.dataset.feedIdentity!.split(':') as [string,keyof FeedIdentity];el.value=String(identities[Number(position)-1]?.[field]??'')});all<HTMLElement>('[data-feed-identity-panel]').forEach((panel)=>{panel.hidden=Number(panel.dataset.feedIdentityPanel)>run.feedCount});all<HTMLButtonElement>('[data-feed-count]').forEach((button)=>button.classList.toggle('active',Number(button.dataset.feedCount)===run.feedCount));setText('[data-live-speedrun="game"]',run.game);setText('[data-live-speedrun="runner"]',run.runner);setText('[data-live-speedrun="layout"]',`${run.feedCount} ${run.feedCount===1?'feed':'feeds'}${run.cameraVisible?' · camera':''}${run.timerVisible?' · timer':''}`);renderDashboardTimer();});
window.setInterval(renderDashboardTimer,100);
let transitionSettingsState=mockTransitionSettings;
observe<ObsState>('obs',mockObs,(obs)=>{const pill=$<HTMLElement>('[data-obs-pill]');pill?.classList.toggle('connected',obs.connected);const status=$('[data-obs-status]');if(status)status.textContent=obs.connected?'OBS connected':'OBS disconnected';const scene=$('[data-obs-scene]');if(scene)scene.textContent=obs.currentProgramScene??obs.host??'';const transition=$<HTMLSelectElement>('[data-obs-transition]');if(transition&&document.activeElement!==transition){const names=obs.availableTransitions?.length?obs.availableTransitions:['Fade','Cut'];transition.innerHTML=names.map((name)=>`<option value="${name}">${name}</option>`).join('');transition.value=names.includes(transitionSettingsState.obsName)?transitionSettingsState.obsName:(obs.currentTransition&&names.includes(obs.currentTransition)?obs.currentTransition:names[0]);}const error=$('[data-obs-error]');if(error)error.textContent=obs.lastError??'';});
observe<TransitionSettings>('transitionSettings',mockTransitionSettings,(raw)=>{const settings=normalizeTransitionSettings(raw);transitionSettingsState=settings;const mode=$<HTMLSelectElement>('[data-transition-mode]');if(mode&&document.activeElement!==mode)mode.value=settings.mode;const transition=$<HTMLSelectElement>('[data-obs-transition]');if(transition&&document.activeElement!==transition)transition.value=settings.obsName;const duration=$<HTMLInputElement>('[data-obs-transition-duration]');if(duration&&document.activeElement!==duration)duration.value=String(settings.durationMs);});
observe<TransitionOverlayState>('transitionOverlay',mockTransitionOverlay,(state)=>{const busy=state.phase==='covering'||state.phase==='revealing';all<HTMLButtonElement>('[data-mode]').forEach((button)=>button.disabled=busy);setText('[data-transition-live-status]',busy?`${state.style} transition · ${state.phase}`:state.error?`Transition recovered: ${state.error}`:'');});
observe<Brand>('brand',mockBrand,(brand)=>{applyBrand(brand);const box=$('[data-swatches]');if(box)box.innerHTML=['primary','secondary','accent','background','panel'].map((key)=>`<i title="${key}" style="background:${brand.colors[key]}"></i>`).join('');setText('[data-brand-background]',brand.assets.background?`Scene background: ${brand.assets.background}`:'Scene background: CSS brand gradient (no image configured)');});
observe<{available:string[];warnings:string[];error?:string}>('brandStatus',{available:['game-grove','hurricon'],warnings:[]},(status)=>{const select=$<HTMLSelectElement>('[data-brand-select]');if(select){const selected=select.value;select.innerHTML=status.available.map((id)=>`<option value="${id}">${id}</option>`).join('');if(status.available.includes(selected))select.value=selected;}const message=$('[data-brand-message]');if(message)message.textContent=status.error??status.warnings.join(' · ');});
observe<string>('activeBrand','game-grove',(id)=>{const select=$<HTMLSelectElement>('[data-brand-select]');if(select)select.value=id;});

all<HTMLButtonElement>('[data-score]').forEach((button)=>button.addEventListener('click',()=>{const [side,delta]=button.dataset.score!.split(':') as ['player1'|'player2',string];if(window.nodecg)void window.nodecg.sendMessage('match:score',{side,delta:Number(delta)});else{const m=matchRep.get();matchRep.set({...m,[side]:{...m[side],score:Math.max(0,m[side].score+Number(delta))}})}}));
$('[data-action="swap"]')?.addEventListener('click',()=>{if(window.nodecg)void window.nodecg.sendMessage('match:swap');else{const m=matchRep.get();matchRep.set({...m,player1:m.player2,player2:m.player1})}});
$('[data-action="reset"]')?.addEventListener('click',()=>{if(!confirm('Reset both scores to zero?'))return;const m=matchRep.get();matchRep.set({...m,player1:{...m.player1,score:0},player2:{...m.player2,score:0}});toast('Scores reset');});
$('[data-action="apply"]')?.addEventListener('click',()=>{const current=matchRep.get();const readPlayer=(side:'player1'|'player2',number:1|2)=>({...current[side],displayName:value(`[data-p${number}="displayName"]`),pronouns:value(`[data-p${number}="pronouns"]`),location:value(`[data-p${number}="location"]`),social:value(`[data-p${number}="social"]`),seed:Number(value(`[data-p${number}="seed"]`))||null});matchRep.set({...current,game:value('[data-field="game"]'),round:value('[data-field="round"]'),bestOf:Number(value('[data-field="bestOf"]'))||null,player1:readPlayer('player1',1),player2:readPlayer('player2',2)});toast('Match info applied');});
all<HTMLButtonElement>('[data-status]').forEach((button)=>button.addEventListener('click',()=>matchRep.set({...matchRep.get(),status:button.dataset.status as MatchState['status']})));
all<HTMLButtonElement>('[data-mode]').forEach((button)=>button.addEventListener('click',()=>{const mode=button.dataset.mode as ShowMode;if(window.nodecg)void window.nodecg.sendMessage('show:setMode',mode);else showRep.set({...showRep.get(),mode});}));
$('[data-action="apply-transition"]')?.addEventListener('click',()=>{const mode=value('[data-transition-mode]') as HbsTransitionMode;const obsName=value('[data-obs-transition]')||'Fade';const durationMs=Number(value('[data-obs-transition-duration]'))||700;const settings=normalizeTransitionSettings({mode,obsName,durationMs});if(window.nodecg)void window.nodecg.sendMessage('transition:set',settings);toast(settings.mode==='obs'?`OBS transition set to ${settings.obsName}`:`HBS ${settings.mode} wipe enabled`);});
all<HTMLButtonElement>('[data-feed-count]').forEach((button)=>button.addEventListener('click',()=>speedrunRep.set({...speedrunRep.get(),feedCount:Number(button.dataset.feedCount) as FeedCount})));
all<HTMLButtonElement>('[data-timer-action]').forEach((button)=>button.addEventListener('click',()=>{const action=button.dataset.timerAction as 'start'|'pause'|'reset';if(action==='reset'&&!confirm('Reset the run timer to zero?'))return;if(window.nodecg)void window.nodecg.sendMessage('speedrun:timer',action);else speedrunRep.set({...speedrunRep.get(),timer:timerAction(speedrunRep.get().timer,action)});}));
$('[data-action="apply-speedrun"]')?.addEventListener('click',()=>{const current=speedrunRep.get();const checked=(name:string)=>$<HTMLInputElement>(`[data-speedrun-toggle="${name}"]`)?.checked??false;const feedIdentities:FeedIdentity[]=Array.from({length:4},(_,index)=>({name:value(`[data-feed-identity="${index+1}:name"]`),pronouns:value(`[data-feed-identity="${index+1}:pronouns"]`),social:value(`[data-feed-identity="${index+1}:social"]`)}));speedrunRep.set({...current,cameraVisible:checked('cameraVisible'),timerVisible:checked('timerVisible'),guidesVisible:checked('guidesVisible'),feedIdentitiesVisible:checked('feedIdentitiesVisible'),feedSocialsVisible:checked('feedSocialsVisible'),feedIdentities,game:value('[data-speedrun="game"]'),platform:value('[data-speedrun="platform"]'),runner:value('[data-speedrun="runner"]'),pronouns:value('[data-speedrun="pronouns"]'),category:value('[data-speedrun="category"]'),estimate:value('[data-speedrun="estimate"]')});toast('Speedrun layout applied');});
all<HTMLButtonElement>('[data-lower-action]').forEach((button)=>button.addEventListener('click',()=>{const current=lowerRep.get();const field=(selector:string,fallback:string|undefined)=>$(selector)?value(selector):fallback;lowerRep.set({...current,visible:button.dataset.lowerAction==='show',title:field('[data-lower="title"]',current.title)??'',subtitle:field('[data-lower="subtitle"]',current.subtitle),tertiary:field('[data-lower="tertiary"]',current.tertiary),style:($( '[data-lower="style"]')?value('[data-lower="style"]'):current.style) as LowerThirdState['style']});}));
$('[data-action="apply-show"]')?.addEventListener('click',()=>{showRep.set({...showRep.get(),currentSegment:value('[data-show="currentSegment"]'),nextSegment:value('[data-show="nextSegment"]'),nextSegmentTime:value('[data-show="nextSegmentTime"]')});toast('Programming updated');});
$('[data-action="add-sponsor"]')?.addEventListener('click',()=>{if(sponsorDraft.length>=12){toast('Sponsor limit is 12');return;}sponsorDraft.push({id:`sponsor-${Date.now()}`,name:'',enabled:true});renderSponsorEditors(sponsorDraft);});
$('[data-action="apply-rail"]')?.addEventListener('click',()=>{
  const sponsors=all<HTMLElement>('[data-sponsor-editor]').map((panel,index)=>({id:sponsorDraft[index]?.id||`sponsor-${index+1}`,name:(panel.querySelector<HTMLInputElement>('[data-sponsor-field="name"]')?.value??'').trim(),logoUrl:(panel.querySelector<HTMLInputElement>('[data-sponsor-field="logoUrl"]')?.value??'').trim()||undefined,enabled:panel.querySelector<HTMLInputElement>('[data-sponsor-field="enabled"]')?.checked??true})).filter((sponsor)=>sponsor.name);
  const donation={total:Number(value('[data-donation="total"]'))||0,goal:Number(value('[data-donation="goal"]'))||0,currency:value('[data-donation="currency"]')||'USD',latestDonor:value('[data-donation="latestDonor"]')||undefined,latestAmount:Number(value('[data-donation="latestAmount"]'))||undefined,latestMessage:value('[data-donation="latestMessage"]')||undefined,updatedAt:Date.now()};
  const enabledModules=Object.fromEntries((['donation','sponsor','announcement','programming'] as RailModule[]).map((module)=>[module,$<HTMLInputElement>(`[data-rail-module-enabled="${module}"]`)?.checked??false])) as Record<RailModule,boolean>;
  const next=normalizeBroadcastRail({...railState,automatic:$<HTMLInputElement>('[data-rail="automatic"]')?.checked??true,rotationSeconds:Number(value('[data-rail="rotationSeconds"]'))||12,enabledModules,donation,announcement:value('[data-rail-announcement]'),sponsors,updatedAt:Date.now()});
  if(window.nodecg)void window.nodecg.sendMessage('rail:update',next);else railRep.set(next);toast('Broadcast rail content applied');
});
all<HTMLButtonElement>('[data-rail-action]').forEach((button)=>button.addEventListener('click',()=>{const action=button.dataset.railAction!;if(window.nodecg)void window.nodecg.sendMessage('rail:control',action);else if(action==='next'||action==='previous')railRep.set(advanceBroadcastRail(railState,action==='next'?1:-1));else railRep.set({...railState,visible:action==='show'?true:action==='hide'?false:railState.visible,held:action==='toggleHold'?!railState.held:railState.held,updatedAt:Date.now()});}));
all<HTMLButtonElement>('[data-rail-module]').forEach((button)=>button.addEventListener('click',()=>{const module=button.dataset.railModule as RailModule;if(window.nodecg)void window.nodecg.sendMessage('rail:setModule',module);else railRep.set({...railState,visible:true,activeModule:module,updatedAt:Date.now()});}));
$('[data-action="set-brand"]')?.addEventListener('click',()=>{const id=value('[data-brand-select]');if(window.nodecg)void window.nodecg.sendMessage('brand:set',id);toast(`Selected ${id}`);});
$('[data-action="reload-brand"]')?.addEventListener('click',()=>{if(window.nodecg)void window.nodecg.sendMessage('brand:reload');toast('Brand files reloaded');});
