import './styles/dashboard.css';
import './styles/transition-dashboard.css';
import { applyBrand } from './brand';
import { mockBrand, mockLowerThird, mockMatch, mockObs, mockShow, mockSpeedrun } from './mock';
import { observe } from './replicant';
import { speedrunFeedIdentities, timerAction, timerElapsed } from './domain';
import type { Brand, FeedCount, FeedIdentity, LowerThirdState, MatchState, ObsState, ShowMode, ShowState, SpeedrunState } from './types';

const $ = <T extends HTMLElement>(selector:string) => document.querySelector<T>(selector);
const all = <T extends HTMLElement>(selector:string) => [...document.querySelectorAll<T>(selector)];
const toast = (message:string) => { const el=$<HTMLElement>('[data-toast]');if(!el)return;el.textContent=message;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2200); };
const value = (selector:string) => ($<HTMLInputElement|HTMLSelectElement>(selector)?.value ?? '').trim();

const matchRep=observe<MatchState>('match',mockMatch,(m)=>{all<HTMLInputElement>('[data-field]').forEach((el)=>{if(document.activeElement!==el)el.value=String(m[el.dataset.field as 'game'|'round'|'bestOf']??'')});(['player1','player2'] as const).forEach((side,i)=>{all<HTMLInputElement>(`[data-p${i+1}]`).forEach((el)=>{if(document.activeElement!==el)el.value=String(m[side][el.dataset[`p${i+1}`] as keyof typeof m[typeof side]]??'')});const out=$<HTMLOutputElement>(`[data-score-value="${side}"]`);if(out)out.value=String(m[side].score)});});
const lowerRep=observe<LowerThirdState>('lowerThird',mockLowerThird,(lower)=>all<HTMLInputElement|HTMLSelectElement>('[data-lower]').forEach((el)=>{if(document.activeElement!==el)el.value=String(lower[el.dataset.lower as keyof LowerThirdState]??'')}));
const showRep=observe<ShowState>('show',mockShow,(show)=>{all<HTMLInputElement>('[data-show]').forEach((el)=>{if(document.activeElement!==el)el.value=String(show[el.dataset.show as keyof ShowState]??'')});all<HTMLButtonElement>('[data-mode]').forEach((button)=>button.classList.toggle('active',button.dataset.mode===show.mode));});
let speedrunState = mockSpeedrun;
const renderDashboardTimer=()=>{const elapsed=timerElapsed(speedrunState.timer);const hours=Math.floor(elapsed/3_600_000);const minutes=Math.floor(elapsed/60_000)%60;const seconds=Math.floor(elapsed/1000)%60;const tenths=Math.floor(elapsed/100)%10;const out=$<HTMLOutputElement>('[data-speedrun-timer]');if(out)out.value=`${hours?`${String(hours).padStart(2,'0')}:`:''}${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}.${tenths}`;};
const speedrunRep=observe<SpeedrunState>('speedrun',mockSpeedrun,(run)=>{speedrunState=run;const identities=speedrunFeedIdentities(run);all<HTMLInputElement>('[data-speedrun]').forEach((el)=>{if(document.activeElement!==el)el.value=String(run[el.dataset.speedrun as keyof SpeedrunState]??'')});all<HTMLInputElement>('[data-speedrun-toggle]').forEach((el)=>{el.checked=Boolean(run[el.dataset.speedrunToggle as keyof SpeedrunState])});all<HTMLInputElement>('[data-feed-identity]').forEach((el)=>{if(document.activeElement===el)return;const [position,field]=el.dataset.feedIdentity!.split(':') as [string,keyof FeedIdentity];el.value=String(identities[Number(position)-1]?.[field]??'')});all<HTMLElement>('[data-feed-identity-panel]').forEach((panel)=>{panel.hidden=Number(panel.dataset.feedIdentityPanel)>run.feedCount});all<HTMLButtonElement>('[data-feed-count]').forEach((button)=>button.classList.toggle('active',Number(button.dataset.feedCount)===run.feedCount));renderDashboardTimer();});
window.setInterval(renderDashboardTimer,100);
observe<ObsState>('obs',mockObs,(obs)=>{const pill=$<HTMLElement>('[data-obs-pill]');pill?.classList.toggle('connected',obs.connected);const status=$('[data-obs-status]');if(status)status.textContent=obs.connected?'OBS connected':'OBS disconnected';const scene=$('[data-obs-scene]');if(scene)scene.textContent=obs.currentProgramScene??obs.host??'';const transition=$<HTMLSelectElement>('[data-obs-transition]');if(transition&&document.activeElement!==transition){const names=obs.availableTransitions?.length?obs.availableTransitions:['Fade','Cut'];transition.innerHTML=names.map((name)=>`<option value="${name}">${name}</option>`).join('');if(obs.currentTransition&&names.includes(obs.currentTransition))transition.value=obs.currentTransition;}const duration=$<HTMLInputElement>('[data-obs-transition-duration]');if(duration&&document.activeElement!==duration&&obs.transitionDurationMs!==undefined)duration.value=String(obs.transitionDurationMs);const error=$('[data-obs-error]');if(error)error.textContent=obs.lastError??'';});
observe<Brand>('brand',mockBrand,(brand)=>{applyBrand(brand);const box=$('[data-swatches]');if(box)box.innerHTML=['primary','secondary','accent','background','panel'].map((key)=>`<i title="${key}" style="background:${brand.colors[key]}"></i>`).join('');});
observe<{available:string[];warnings:string[];error?:string}>('brandStatus',{available:['game-grove','hurricon'],warnings:[]},(status)=>{const select=$<HTMLSelectElement>('[data-brand-select]');if(select){const selected=select.value;select.innerHTML=status.available.map((id)=>`<option value="${id}">${id}</option>`).join('');if(status.available.includes(selected))select.value=selected;}const message=$('[data-brand-message]');if(message)message.textContent=status.error??status.warnings.join(' · ');});
observe<string>('activeBrand','game-grove',(id)=>{const select=$<HTMLSelectElement>('[data-brand-select]');if(select)select.value=id;});

all<HTMLButtonElement>('[data-score]').forEach((button)=>button.addEventListener('click',()=>{const [side,delta]=button.dataset.score!.split(':') as ['player1'|'player2',string];if(window.nodecg)void window.nodecg.sendMessage('match:score',{side,delta:Number(delta)});else{const m=matchRep.get();matchRep.set({...m,[side]:{...m[side],score:Math.max(0,m[side].score+Number(delta))}})}}));
$('[data-action="swap"]')?.addEventListener('click',()=>{if(window.nodecg)void window.nodecg.sendMessage('match:swap');else{const m=matchRep.get();matchRep.set({...m,player1:m.player2,player2:m.player1})}});
$('[data-action="reset"]')?.addEventListener('click',()=>{if(!confirm('Reset both scores to zero?'))return;const m=matchRep.get();matchRep.set({...m,player1:{...m.player1,score:0},player2:{...m.player2,score:0}});toast('Scores reset');});
$('[data-action="apply"]')?.addEventListener('click',()=>{const current=matchRep.get();const readPlayer=(side:'player1'|'player2',number:1|2)=>({...current[side],displayName:value(`[data-p${number}="displayName"]`),pronouns:value(`[data-p${number}="pronouns"]`),location:value(`[data-p${number}="location"]`),social:value(`[data-p${number}="social"]`),seed:Number(value(`[data-p${number}="seed"]`))||null});matchRep.set({...current,game:value('[data-field="game"]'),round:value('[data-field="round"]'),bestOf:Number(value('[data-field="bestOf"]'))||null,player1:readPlayer('player1',1),player2:readPlayer('player2',2)});toast('Match info applied');});
all<HTMLButtonElement>('[data-status]').forEach((button)=>button.addEventListener('click',()=>matchRep.set({...matchRep.get(),status:button.dataset.status as MatchState['status']})));
all<HTMLButtonElement>('[data-mode]').forEach((button)=>button.addEventListener('click',()=>{const mode=button.dataset.mode as ShowMode;if(window.nodecg)void window.nodecg.sendMessage('show:setMode',mode);else showRep.set({...showRep.get(),mode});}));
$('[data-action="apply-transition"]')?.addEventListener('click',()=>{const name=value('[data-obs-transition]');const durationMs=Number(value('[data-obs-transition-duration]'))||undefined;if(window.nodecg)void window.nodecg.sendMessage('obs:setTransition',{name,durationMs});toast(`Transition set to ${name}`);});
all<HTMLButtonElement>('[data-feed-count]').forEach((button)=>button.addEventListener('click',()=>speedrunRep.set({...speedrunRep.get(),feedCount:Number(button.dataset.feedCount) as FeedCount})));
all<HTMLButtonElement>('[data-timer-action]').forEach((button)=>button.addEventListener('click',()=>{const action=button.dataset.timerAction as 'start'|'pause'|'reset';if(action==='reset'&&!confirm('Reset the run timer to zero?'))return;if(window.nodecg)void window.nodecg.sendMessage('speedrun:timer',action);else speedrunRep.set({...speedrunRep.get(),timer:timerAction(speedrunRep.get().timer,action)});}));
$('[data-action="apply-speedrun"]')?.addEventListener('click',()=>{const current=speedrunRep.get();const checked=(name:string)=>$<HTMLInputElement>(`[data-speedrun-toggle="${name}"]`)?.checked??false;const feedIdentities:FeedIdentity[]=Array.from({length:4},(_,index)=>({name:value(`[data-feed-identity="${index+1}:name"]`),pronouns:value(`[data-feed-identity="${index+1}:pronouns"]`),social:value(`[data-feed-identity="${index+1}:social"]`)}));speedrunRep.set({...current,cameraVisible:checked('cameraVisible'),timerVisible:checked('timerVisible'),guidesVisible:checked('guidesVisible'),feedIdentitiesVisible:checked('feedIdentitiesVisible'),feedSocialsVisible:checked('feedSocialsVisible'),feedIdentities,game:value('[data-speedrun="game"]'),platform:value('[data-speedrun="platform"]'),runner:value('[data-speedrun="runner"]'),pronouns:value('[data-speedrun="pronouns"]'),category:value('[data-speedrun="category"]'),estimate:value('[data-speedrun="estimate"]')});toast('Speedrun layout applied');});
all<HTMLButtonElement>('[data-lower-action]').forEach((button)=>button.addEventListener('click',()=>{const current=lowerRep.get();lowerRep.set({...current,visible:button.dataset.lowerAction==='show',title:value('[data-lower="title"]'),subtitle:value('[data-lower="subtitle"]'),tertiary:value('[data-lower="tertiary"]'),style:value('[data-lower="style"]') as LowerThirdState['style']});}));
$('[data-action="apply-show"]')?.addEventListener('click',()=>{showRep.set({...showRep.get(),currentSegment:value('[data-show="currentSegment"]'),nextSegment:value('[data-show="nextSegment"]'),nextSegmentTime:value('[data-show="nextSegmentTime"]')});toast('Programming updated');});
$('[data-action="set-brand"]')?.addEventListener('click',()=>{const id=value('[data-brand-select]');if(window.nodecg)void window.nodecg.sendMessage('brand:set',id);toast(`Selected ${id}`);});
$('[data-action="reload-brand"]')?.addEventListener('click',()=>{if(window.nodecg)void window.nodecg.sendMessage('brand:reload');toast('Brand files reloaded');});
